yii/ejemplos/aplicacion1/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;



class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        // esta es la accion que se ejecuta por defecto
        return $this->render('index'); // renderiza la vista index
    }

    
    


    

    public function actionMensaje(){
        return $this->render('mostrarMensaje');
    }

    public function actionImagen(){
        return $this->render('imagen');
    }

    public function actionDias(){
        return $this->render('dias');
    }

    public function actionMeses(){
        return $this->render('meses');
    }

    public function actionImagenes(){
        return $this->render('imagenes');
    }
}
    

yii/ejemplos/aplicacion1/views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap5\Breadcrumbs;
use yii\bootstrap5\Html;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;

AppAsset::register($this);

$this->registerCsrfMetaTags();
$this->registerMetaTag(['charset' => Yii::$app->charset], 'charset');
$this->registerMetaTag(['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no']);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['meta_description'] ?? '']);
$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['meta_keywords'] ?? '']);
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => Yii::getAlias('@web/favicon.ico')]);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header id="header">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => ['class' => 'navbar-expand-md navbar-dark bg-dark fixed-top']
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
           
            ['label' => 'Mensaje', 'url' => ['/site/mensaje']],
            ['label' => 'Imagen', 'url' => ['/site/imagen']],
            ['label' => 'Dias', 'url' => ['/site/dias']],
            ['label' => 'Meses', 'url' => ['/site/meses']],
            ['label' => 'Imagenes', 'url' => ['/site/imagenes']],


        ] 
    ]);
    NavBar::end();
    ?>
</header>

<main id="main" class="flex-shrink-0" role="main">
    <div class="container">
        <?php if (!empty($this->params['breadcrumbs'])): ?>
            <?= Breadcrumbs::widget(['links' => $this->params['breadcrumbs']]) ?>
        <?php endif ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer id="footer" class="mt-auto py-3 bg-light">
    <div class="container">
        <div class="row text-muted">
            <div class="col-md-6 text-center text-md-start">&copy; My Company <?= date('Y') ?></div>
            <div class="col-md-6 text-center text-md-end"><?= Yii::powered() ?></div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

yii/ejemplos/aplicacion1/views/site/dias.php
<ul>
    <li>Lunes</li>
    <li>Martes</li>
    <li>Miercoles</li>
    <li>Jueves</li>
    <li>Viernes</li>
    <li>Sabado</li>
    <li>Domingo</li>
</ul>

yii/ejemplos/aplicacion1/views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

yii/ejemplos/aplicacion1/views/site/imagen.php
<?php

use yii\helpers\Html;
?>
<h2>
    Imagen
</h2>

<?= Html::img('@web/imgs/foto1.jpg',// ruta
[
   'alt' => 'ojo', // atributos de la etiqueta texto alternativo
   'class' => 'rounded img-thumbnail col-sm-6', // atributos de la tiqueta

]) ?>

yii/ejemplos/aplicacion1/views/site/imagenes.php
<?php

use yii\helpers\Html;
?>
<h2>
    Imagenes
</h2>

<?= Html::img('@web/imgs/foto2.jpg')?>

<?= Html::img('@web/imgs/foto3.jpg')?>
<?= Html::img('@web/imgs/foto4.jpg')?>

<?= Html::img('@web/imgs/foto5.jpg')?>

yii/ejemplos/aplicacion1/views/site/index.php
<?php

/** @var yii\web\View $this */

$this->title = 'Aplicacion 1 de clase';
?>
<div>
    <h1>Pagina de inicio</h1>
</div>

yii/ejemplos/aplicacion1/views/site/meses.php
<ul>
    <li>Enero</li>
    <li>Febrero</li>
    <li>Marzo</li>
    <li>Abril</li>
    <li>Mayo</li>
    <li>Junio</li>
    <li>Julio</li>
</ul>

yii/ejemplos/aplicacion1/views/site/mostrarMensaje.php
<h2>
    Esta vista nos muestra un mensaje
</h2>
<div>
    Hola
</div>